version: '3.8'

services:
  app:
    build: .  # Build the Docker image using the Dockerfile in the current directory
    container_name: my_fastapi_container  # Name of the container
    env_file:
      - .env  # Load environment variables from a .env file
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000
    command: uvicorn app:app --host 0.0.0.0 --port 8000  # Command to run the app