# This file defines all the base models for the fastapi
from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    question: str
    id: str = None


class ChatResponse(BaseModel):
    id: str
    response: str
    reference_question_id: str = None
    log_id: str = None


# Pydantic model for the response schema with detailed parameter descriptions
class ChatLog(BaseModel):
    id: str = Field(
        ..., description="Unique identifier for the chat log, generated by MongoDB."
    )
    user_id: str = Field(
        ..., description="Unique identifier for the user who submitted the question."
    )
    question: str = Field(
        ..., description="The user's question submitted to the system."
    )
    answer: str = Field(
        ..., description="The system's response to the user's question."
    )
    chat_id: str = Field(
        ...,
        description="Unique identifier for the chat session to which this log belongs.",
    )
    reference_question_id: str = Field(
        ...,
        description="Unique identifier for the specific question within the chat session.",
    )
    timestamp: str = Field(
        ...,
        description="Timestamp indicating when the log entry was created in ISO 8601 format.",
    )
